### ISSUE TITLE
unable to run `app.py` might be issue with dependency

### ISSUE THREAD

**Issue by kumarvivek1752** [aitrepreneur/INSTID#1]
unable to download `https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip`
it also not found on github.
<img width="885" alt="image" src="https://github.com/aitrepreneur/INSTID/assets/67893205/061a5d00-649b-4226-a5aa-583ecba732c7">

my logs:
```

(.venv) ➜ INSTID git:(main) python app.py
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
download_path: ./models\antelopev2
Downloading ./models\antelopev2.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip...
Traceback (most recent call last):
  File "D:\program\INSTID\app.py", line 45, in <module>
    app = FaceAnalysis(name='antelopev2', root='./', providers=['CPUExecutionProvider'])
  File "D:\program\INSTID\.venv\lib\site-packages\insightface\app\face_analysis.py", line 27, in __init__
    self.model_dir = ensure_available('models', name, root=root)
  File "D:\program\INSTID\.venv\lib\site-packages\insightface\utils\storage.py", line 28, in ensure_available
    return download(sub_dir, name, force=False, root=root)
  File "D:\program\INSTID\.venv\lib\site-packages\insightface\utils\storage.py", line 17, in download
    download_file(model_url,
  File "D:\program\INSTID\.venv\lib\site-packages\insightface\utils\download.py", line 73, in download_file
    raise RuntimeError("Failed downloading url %s" % url)
RuntimeError: Failed downloading url https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip
(.venv) ➜ INSTID git:(main)
```

**Comment by rondlite** [comment]
they at version buffalo and removed antilope ..
https://github.com/deepinsight/insightface/releases

**Comment by aitrepreneur** [comment]
I put antelopev2 files in this repo: https://huggingface.co/Aitrepreneur/models

**Comment by kumarvivek1752** [comment]
i fixed this error by manually downloading [antelopev2.zip](https://drive.google.com/file/d/18wEUfMNohBJ4K3Ly5wpTejPfDzp-8fI8/view?usp=sharing ) and extract inside the `./models` folder

source: https://github.com/deepinsight/insightface/issues/1896#issuecomment-1023867304


@aitrepreneur by the way Image generation took very long time, it takes around `1200 sec` to generate a image 

my laptop conf: 
```bash
CPU: 13th Gen Intel(R) Core(TM) i7-13700HX @ 2.304GHz
GPU: NVIDIA GeForce RTX 4060 Laptop GPU 8gb vram
GPU: Intel(R) UHD Graphics
Memory: 8.63 GiB / 15.73 GiB (54%)
```
is it normal with my laptop? or it should be improved? L'm asking because stable diffusion does not takes this much time to generate a decent image it takes only 1 or 2 min or less

**Comment by kyuumeitai** [comment]
It also happened to me @kumarvivek1752 but I check the youtube video and discovered that I haven't git lfs and also miss the step that clones the aitrepreneur's huggingface.
