### ISSUE TITLE
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by KurtCocain** [aitrepreneur/INSTID#3]
https://stackoverflow.com/questions/75641074/i-run-stable-diffusion-its-wrong-runtimeerror-layernormkernelimpl-not-implem

Suggests commandline_args = os.environ.get('COMMANDLINE_ARGS', "--skip-torch-cuda-test --no-half") to fix it somewhere in the launch.
I am no saavy and no idea if that's even relevent but I can't use the collab because of that error.
maybe theres something even better somewhere :)

**Comment by aitrepreneur** [comment]
no need, you just need to select a GPU, just click on the connect arrow option, change runtime type, under Hardware accelerator check the T4 GPU then click save. Then run the cells.

**Comment by KurtCocain** [comment]
![image](https://github.com/aitrepreneur/INSTID/assets/19999692/156a4b68-a75e-4663-82d0-54e5d6e1f881)
Oh i am stupid.
Thanks.
